from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(536, 714)
        MainWindow.setWindowIcon(QIcon('assets/logo.svg'))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(210, 30, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(36)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 110, 431, 481))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.guesses_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.guesses_layout.setContentsMargins(0, 0, 0, 0)
        self.guesses_layout.setObjectName("guesses_layout")
        self.input_box = QtWidgets.QLineEdit(self.centralwidget)
        self.input_box.setGeometry(QtCore.QRect(160, 610, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(18)
        self.input_box.setFont(font)
        self.input_box.setObjectName("input_box")
        self.enter_button = QtWidgets.QPushButton(self.centralwidget)
        self.enter_button.setGeometry(QtCore.QRect(330, 610, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(16)
        self.enter_button.setFont(font)
        self.enter_button.setObjectName("enter_button")
        self.enter_button.setIcon(QtGui.QIcon('assets/enter.png'))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 536, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wordle"))
        self.title.setText(_translate("MainWindow", "WORDLE"))
        self.enter_button.setText(_translate("MainWindow", ""))
